### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kkofler** [Timeroot/JNA_SCIP#1]
I was unable to find a license statement anywhere in this repository. This means that, unless I have missed something, the default under copyright law applies, and unfortunately, that means we are essentially not allowed to do anything with your code.

Please put an explicit license on your code. It should be sufficiently permissive and compatible with the SCIP license. (In particular, the GNU GPL would be very unsuitable because of its strong copyleft/share-alike provision that conflicts with the SCIP license.)

I would suggest:
* either the MIT license used in JSCIPOpt: https://github.com/scipopt/JSCIPOpt/blob/master/LICENSE
* or the Apache License (version 2.0): https://www.apache.org/licenses/LICENSE-2.0

**Comment by Timeroot** [comment]
Done, thanks!
